language: python
before_install:
- pip install pycodestyle
install:
- pip install -r requirements.txt
- python setup.py install
script:
- find . -name \*.py -exec pycodestyle --max-line-length=120 --ignore=E402 {} +
- pytest --cov=tpDcc
- sphinx-apidoc -f -e -o docs/sphinx tpDcc
- sphinx-build -M html ./docs/sphinx ./
after_success:
- coveralls
- cd html && touch .nojekyll && cd ../
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: "$GITHUB_TOKEN"
    keep_history: true
    local_dir: html
    on:
      branch: master
  - provider: pypi
    skip_cleanup: true
    user: tpoveda
    password:
      secure: d0S1YVDdYWGxVHhm4k0A6yx7ZIVp2eplOowHJFxtjVWbcj9MLtP98BShFjwhsDZND88CZnm40nDD0+uapqpuCRmSgar99QY8k7CSP0SvSMV7N74UPj1ezE5KElOGAJ7TUqvascsTjCAE5v8sCfnXzHSRwssEBQ8/VNq3jrdeit3Hks8Vmg/oZ2mekgrFhtrXdsV0SmvU1sm89XQeDtzmTzeBZwz50Qu7a/71MqeTCGaIkU+4hraHR/vLh5Sj87hX61JX8RyfxjCkl3mP0nHCBgJQx2ih77IxKRtMiSCxTVPClTKU/UrQzZDkw5RCVjsd2EWLfWpRbY9RZHNl4gApN1tdajwaNKf6L7Rc0N605al+saaAPr8lL39XHakyGNaYIX4XJsZC1DOjFUWrWwXGKgl3XkWf5+7OKcmzI/DT20sSHfUZ5lVOa48PfMp68zna0z/ENsaoGllM/7tlHRNUwIEId8pxU6yIVa8svoptkGPi6N5dFOKTsv23cyZNxT+/o03tKQVo/k6nlc3JyxjObwRZ1LGxr7GsWxBHOCfi1j+BpSXF1OXl+e6+R+I3noJch1NIrphWpOSvyIBGlGApU/OLgaZY+Eke2OuUTICO8bw1TH6vQ9Wq/uXgzogdo0h3SpqUUjpbavZyNYD++A5Iyx5zXOlWUX/D5a/3VDq44rg=
    on:
      branch: master
      tags: true